### ISSUE TITLE
Changes to jakartablogs.ee

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartablogs.ee#10]
1) The tab for the website should read "Jakarta Blogs", not "Planet Jakarta" only because the twitter handle is "@JakartaEEBlogs", the branding would be off if we called the website tab "Planet Jakarta"

2) The logo in the top left corner of jakartablogs.ee should bring you back to jakarta.ee

3) Remove the donate button

4) The "more" dropdown in the navigation should link to Jakarta.ee pages:
About Jakarta EE - https://jakarta.ee/about/
Frequently Asked Questions - https://jakarta.ee/about/faq/
Become a Member - https://jakarta.ee/members/
Stay Connected  -  https://jakarta.ee/connect/
2018 Developer Survey - https://jakarta.ee/news/2018/04/24/jakarta-ee-community-survey/
Working Group Charter - https://eclipse.org/org/workinggroups/jakarta_ee_charter.php
Technical Direction - https://www.eclipse.org/ee4j/direction.php
Newsletter Archives - https://jakarta.ee/newsletter
Meeting Minutes - https://jakarta.ee/meeting_minutes
Trademark Guidelines - https://jakarta.ee/legal/trademark_guidelines/

5) The top-level navigation on Jakarta.ee homepage should include Blog linked to Jakartablogs.ee

6) Please add link to Jakarta Blogs on https://jakarta.ee/connect/
Visit Jakartablogs.ee to stay updated with posts from our global community on Jakarta EE news, technologies, best practices, and compatible products.

**Comment by ThabangMash** [comment]
7. Please add RSS 2.0 icon to the page pointing to https://jakartablogs.ee/rss20.xml
Suggest putting in upper right-hand corner (next to button to follow JakartaEEBlogs on Twitter)

**Comment by chrisguindon** [comment]
I believe that all these changes has been implemented!

Closing this bug but if something is missing, please re-open with more information!

Thanks,
