### ISSUE TITLE
Submition og JEE.gr feed to jakartablogs.ee

### ISSUE THREAD

**Issue by diakogiannis** [jakartaee/jakartablogs.ee#112]
**Blog RSS Feed URL:
https://jee.gr/ and feed url https://jee.gr/feed/

**Author Name"
Alexius DIAKOGIANNIS

**Why should we add this blog to Jakartablogs.ee?
I am contantly blogging on this blog for JavaEE related issues. It has content regarding Java, application servers, security, microservices and everything around them. 

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.
![1673385886470-185x185](https://github.com/jakartaee/jakartablogs.ee/assets/20904915/c0bd1fb5-c612-4c2a-a42c-72b198d75260)

**Comment by oliviergoulet5** [comment]
I will close this issue since your blog has been added for quite some time now!
