### ISSUE TITLE
Add Dmitry's blog

### ISSUE THREAD

**Issue by m0mus** [jakartaee/jakartablogs.ee#15]
**Blog RSS Feed URL:
https://dmitrykornilov.net/rss

**Author Name"
Dmitry Kornilov

**Why should we add this blog to Jakartablogs.ee?
I am an active Jakarta EE contributor from Oracle and EE4J PMC member. My blog contains articles mainly about Jakarta EE/Microprofile.

** Profile Picture:
![Dmitry Kornilov](https://user-images.githubusercontent.com/9343261/51871727-798e3300-2357-11e9-9904-b856233e57ad.jpg)

**Comment by chrisguindon** [comment]
Thank you! Your post should appear in the next 20 minutes or so!
