### ISSUE TITLE
Payara request for Jakartablogs.ee

### ISSUE THREAD

**Issue by Jadonblade** [jakartaee/jakartablogs.ee#18]
**Blog RSS Feed URL:
https://blog.payara.fish/topic/jakartaee/rss.xml

**Author Name"
The Payara Team

**Why should we add this blog to Jakartablogs.ee?
As strategic members of Jakarta EE we have enjoyed writing many blogs relevant to a Jakarta EE audience. This feed uses a topic tag so will pull in any new Jakarta EE blogs we write. 

** Profile Picture:
![payara square](https://user-images.githubusercontent.com/16439974/51918932-5789c480-23da-11e9-9eb2-db37dc9b4238.png)

**Comment by chrisguindon** [comment]
Thank you! 

Your posts should appear on the website in the next 20 minutes or so!
