### ISSUE TITLE
adambien.blog request for Jakartablogs.ee

### ISSUE THREAD

**Issue by AdamBien** [jakartaee/jakartablogs.ee#19]
![abien](https://user-images.githubusercontent.com/891845/51926711-27e6b680-23f2-11e9-9bd6-4594b54312ae.png)
**Blog RSS Feed URL:
http://www.adam-bien.com/roller/abien/feed/entries/rss

**Author Name"
Adam Bien

**Why should we add this blog to Jakartablogs.ee?
Java / Java EE code samples

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by chrisguindon** [comment]
Thank you! 

Your posts should appear on the website in the next 20 minutes or so!
