### ISSUE TITLE
Kodnito.com blog request for Jakartablogs.ee

### ISSUE THREAD

**Issue by cicekhayri** [jakartaee/jakartablogs.ee#21]
![143997](https://user-images.githubusercontent.com/143997/51942885-727b2980-2418-11e9-9e94-bd4b09867e14.png)

**Blog RSS Feed URL:
https://kodnito.com/rss

**Author Name"
Hayri Cicek

**Why should we add this blog to Jakartablogs.ee?
I write tutorials mainly about Jakarta EE / MicroProfile

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by chrisguindon** [comment]
Thank you! 

Your posts should appear on the website in the next 20 minutes or so!
