### ISSUE TITLE
Eclipse Glassfish 5.1 is Java EE 8 Compatible!  What's next?

### ISSUE THREAD

**Issue by kwsutter** [jakartaee/jakartablogs.ee#23]
**Blog RSS Feed URL:
https://developer.ibm.com/announcements/eclipse-glassfish-51-is-java-ee-8-compatible/

**Author Name"
Kevin Sutter

**Why should we add this blog to Jakartablogs.ee?
My views on the Glassfish 5.1 release and what's on the horizon for the wider Jakarta EE team.

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by kwsutter** [comment]
Only feeds are allowed?  That's kind of limiting, isn't it?  If I give you the IBM Developer feed, you're going to get a lot of blog entries.  Some of which are Jakarta related, others may not...

**Comment by chrisguindon** [comment]
I would recommend using categories/tags to filter your feed which should only include posts that are related to Jakarta EE.

**Comment by kwsutter** [comment]
Hi @chrisguindon, can we try this feed url?  This is specific to my blog post.
https://developer.ibm.com/announcements/eclipse-glassfish-51-is-java-ee-8-compatible/feed

If this works okay, then I can open a separate issue to get our Jakarta-related blog feed.

Thanks! Kevin

**Comment by kwsutter** [comment]
Bump...  Will these individual blog feeds work?  Or, do we need a more elaborate filter system for the IBM Developer blog feed?  Thanks!

**Comment by chrisguindon** [comment]
i would prefer one feed per author or organization otherwise I need to get involved each time a new post is submitted.

**Comment by kwsutter** [comment]
Fair enough...  Sorry for the delay in responding.  Our Think conference was last week and it's finally settling down...  Thanks.

**Comment by chrisguindon** [comment]
No worries!

Closing this issue!
