### ISSUE TITLE
vorozco.com blog request for Jakartablogs.ee

### ISSUE THREAD

**Issue by tuxtor** [jakartaee/jakartablogs.ee#24]
**Blog RSS Feed URL:
http://feeds.feedburner.com/the-j?format=xml

**Author Name"
Víctor Orozco

**Why should we add this blog to Jakartablogs.ee?
I write posts over Jakarta EE and extensions -e.g. DeltaSpike, MicroProfile-, covering book reviews, IDEs, extensions  and events in Latin America

** Profile Picture:
![me_vorozco com](https://user-images.githubusercontent.com/126580/52073889-38ac3f00-254e-11e9-96fc-40bcb8195da9.jpg)

**Comment by chrisguindon** [comment]
Thank you! 

Your posts should appear on the website in the next 20 minutes or so!
