### ISSUE TITLE
Ivo Woltring request for Jakartablogs.ee

### ISSUE THREAD

**Issue by IvoNet** [jakartaee/jakartablogs.ee#29]
![ivo woltring_portrait_185x185](https://user-images.githubusercontent.com/741238/52670493-f94ffc00-2f18-11e9-9442-7b0e6334d61b.jpg)

**Blog RSS Feed URL: 
https://www.ivonet.nl/atom.xml
Filter on `<category term="jakarta-ee" scheme="http://www.ivonet.nl/categories/jakarta-ee/"/>` to get the more jakarta-ee related content

**Author Name"
Ivo Woltring

**Why should we add this blog to Jakartablogs.ee?
I love writing blogs blogs relevant to a Jakarta EE audience. 

** Profile Picture:
If you wish to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by ericpoirier** [comment]
Hi,

Your feed was added to the Jakarta EE blogs website.

Thanks.
