### ISSUE TITLE
Edwin Derks author request for jakartablogs.ee

### ISSUE THREAD

**Issue by ederks85** [jakartaee/jakartablogs.ee#30]
**Blog RSS Feed URL:
https://www.cloudnativesolutions.guru/category/jakarta-ee/feed/

**Author Name"
Edwin Derks

**Why should we add this blog to Jakartablogs.ee?
I am a Java EE / Jakarta EE / MicroProfile enthousiast that wants to contribute to the evolution of the platform.

I am working with Java EE on a daily basis and giving lectures, workshops and conference talks about it. Next to that, I am writing related articles in NLJUG's Java Magazine in the Netherlands. I would like to extend my writings to jakartablogs.ee in order to reach out to, and create content for the whole community.

** Profile Picture:
https://nl.gravatar.com/userimage/91524624/0eec336bd00ee564bb6cecec27c6466c.jpg?size=185

**Comment by ericpoirier** [comment]
Hi,

Your feed was added to the Jakarta EE blogs website.

Thanks.
