### ISSUE TITLE
blog.sebastian-daschner.com request for jakartablogs.ee

### ISSUE THREAD

**Issue by sdaschner** [jakartaee/jakartablogs.ee#31]
**Blog RSS Feed URL:
https://blog.sebastian-daschner.com

**Author Name"
Sebastian Daschner

**Why should we add this blog to Jakartablogs.ee?
Writing tips, tutorials, and thoughts on Java EE, Jakarta EE, and MicroProfile.

** Profile Picture:
![sebastian2](https://user-images.githubusercontent.com/6815170/52961710-6bc53f80-3350-11e9-96f3-eeaf73386542.jpg)

**Comment by ericpoirier** [comment]
Hi,

Your feed was added to the Jakarta EE blogs website.

Thanks.
