### ISSUE TITLE
rieckpil.de request for Jakarta EE blogs

### ISSUE THREAD

**Issue by rieckpil** [jakartaee/jakartablogs.ee#33]
**Blog RSS Feed URL:

https://rieckpil.de/category/jakarta-ee/feed/

**Author Name"

Philip Riecks

**Why should we add this blog to Jakartablogs.ee?

Blogging about Java EE/Jakarte EE and Java in general.

** Profile Picture:

![profilbild_1](https://user-images.githubusercontent.com/14176609/53038716-b1cbf180-347d-11e9-9aec-5433bd5ceaad.jpg)

**Comment by ericpoirier** [comment]
Hi,

Your feed was added to the Jakarta EE blogs website.

Thanks.
