### ISSUE TITLE
Fix Adam B. link to his website under his picture in all his blogs

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakartablogs.ee#36]
**Blog RSS Feed URL:
For example: https://blogs.eclipse.org/blog/180/feed

**Author Name"
The name of the author for this blog.

**Why should we add this blog to Jakartablogs.ee?
Describe in your own words what this blog is about and why we should add this new blog to jakartablogs.ee.

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by chrisguindon** [comment]
The problem is with the author rss feed:
view-source:http://adambien.blog/roller/abien/feed/entries/rss

http://adambien.blog/roller
The website is using the link value for the link to the blog!

**Comment by chrisguindon** [comment]
Closing this issue since url used on the site is listed in Adam RSS feed: http://adambien.blog/roller/abien/feed/entries/rss
