### ISSUE TITLE
Fix link to Adam Bien's blog

### ISSUE THREAD

**Issue by stephanieswart** [jakartaee/jakartablogs.ee#38]
Adam Bien's blog link is currently: http://adambien.blog/roller, please change it to http://adambien.blog/

**Comment by chrisguindon** [comment]
The problem is with the author rss feed:
view-source:http://adambien.blog/roller/abien/feed/entries/rss

 <link>http://adambien.blog/roller</link>

The website is using the link value for the link to the blog!

**Comment by chrisguindon** [comment]
Closing since this is a dup of #36
