### ISSUE TITLE
Kodcu.com feed request for Jakarta EE blogs

### ISSUE THREAD

**Issue by altuga** [jakartaee/jakartablogs.ee#45]
**Blog RSS Feed URL:
https://kodcu.com/feed

**Author Name"
Altuğ B. Altıntaş

**Why should we add this blog to Jakartablogs.ee?
I'm continuously experimenting and learning new staff about Jakarta EE and Microprofile and I would like to share my results with the others

** Profile Picture:
https://drive.google.com/file/d/1DA83qwLKCwRWyui-j4M3Xvwo7WNyQNi7/view?usp=sharing

**Comment by ericpoirier** [comment]
Hi Altuğ,

You blog was added to the jakartablogs.ee website. We will see the update in a few minutes.

Please reopen this issue if there's a problem with this update.

Thanks.

**Comment by altuga** [comment]
I couldn't see my blog post at https://jakartablogs.ee/#main-content address
