### ISSUE TITLE
Add Webtide blog

### ISSUE THREAD

**Issue by gregw** [jakartaee/jakartablogs.ee#48]
**Blog RSS Feed URL:
https://webtide.com/feed/

**Author Name"
Webtide Blog

**Why should we add this blog to Jakartablogs.ee?
This is the primary blog discussing the development of the Jetty servlet container and websocket server.
It contains the blogs of Greg Wilkins, and Joakim Erdfelt, who are bother Jakarta EE spec leads (Servlet and Websocket), plus the blogs of all the key developers of Jetty. 

** Profile Picture:
https://webtide.com/wp-content/uploads/2017/01/cropped-WTLogo-2.png
or 
https://www.eclipse.org/jetty/images/jetty-logo-80x22.png

**Comment by ericpoirier** [comment]
Hi,

I can see that the last blog post is about Jakarta EE but the other ones that I see are not Jakarta EE specific.

Is there a way you can provide an RSS feed that would include only Jakarta EE related blog posts?

Thanks.

**Comment by gregw** [comment]
@ericpoirier The blog is primarily about the Jetty servlet container, which is an implementation of several EE API.   It's essentially a subset of APIs implemented by Payara, which is included in the ee blogs!

**Comment by gregw** [comment]
@ericpoirier We've created a tag jakarta and will tag relevant articles: https://webtide.com/category/jakarta/feed/

**Comment by ericpoirier** [comment]
Hi,

Your blog was just added to the website. We should see the posts as soon as the site is done rebuilding.
