### ISSUE TITLE
Jakarta NoSQL: The Main Idea Behind the API

### ISSUE THREAD

**Issue by otaviojava** [jakartaee/jakartablogs.ee#49]
* **Blog RSS Feed URL:** https://dzone.com/articles/jakarta-nosql-the-main-idea-behind-the-api

* **Author Name** Otavio Santana
* **Why should we add this blog to Jakartablogs.ee?**
This post explains why Jakarta NoSQL would use the divide-and-conquer strategy as an initial step.
* **Profile Picture:** https://dz2cdn4.dzone.com/thumbnail?fid=10682107&w=240

**Comment by ericpoirier** [comment]
Hi Otavio,

On the Jakartablogs.ee website we add RSS feeds of other blogs that talks about Jakarta EE. We can't add a single blog post to the site, its not how the blog site was built.

Is there a way you can provide an RSS link of your blog post?

Thanks.

**Comment by otaviojava** [comment]
I'll look for it.
