### ISSUE TITLE
OpenLiberty.io blog feed for Jakarta EE

### ISSUE THREAD

**Issue by kwsutter** [jakartaee/jakartablogs.ee#50]
**Blog RSS Feed URL:
https://openliberty.io/jakartaee.xml

**Author Name"
Multiple authors.  We are tagging our blogs with "Jakarta EE" that are related to Jakarta EE.  Do we have to only have a single author?

**Why should we add this blog to Jakartablogs.ee?
We have a blogging area on openliberty.io.  When we post articles related to Jakarta EE, we would like to get them aggregated on the Jakarta EE blog site as well.

** Profile Picture:
If you wish to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by ericpoirier** [comment]
Hi,

Thanks for submitting your blog, it has been added to the jakartablogs.ee website. You should see it in a few minutes.
