### ISSUE TITLE
Could you please add my blog?

### ISSUE THREAD

**Issue by nheidloff** [jakartaee/jakartablogs.ee#53]
**Blog RSS Feed URL:
For example: http://heidloff.net/tag/java/feed/

**Author Name"
Niklas Heidloff

**Why should we add this blog to Jakartablogs.ee?
Thabang Mashologu asked me and I'd like to share my latest Java samples with the community

** Profile Picture:
![nh](https://user-images.githubusercontent.com/1425685/58257852-f2375600-7d71-11e9-808c-a693a7101bad.jpg)

**Comment by ericpoirier** [comment]
Hi Niklas,

Your blog was just added to the website. We should see the posts as soon as the site is done rebuilding.
