### ISSUE TITLE
Please add my blog to Jakarta Blogs

### ISSUE THREAD

**Issue by dheffelfinger** [jakartaee/jakartablogs.ee#54]
**Blog RSS Feed URL:
http://mail.ensode.net/roller/dheffelfinger/feed/entries/atom?cat=%2FJakarta+EE

**Author Name"
David R. Heffelfinger

**Why should we add this blog to Jakartablogs.ee?
I've been involved with Java EE / Jakarta EE for a long time. I have written several books on the topic, as well as giving conference talks and acting as a Java EE instructor.

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by ericpoirier** [comment]
Hi David,

Your blog was just added to the website. We should see the posts as soon as the site is done rebuilding.
