### ISSUE TITLE
Summary of Community Retrospective on Jakarta EE 8 Release

### ISSUE THREAD

**Issue by will-lyons** [jakartaee/jakartablogs.ee#60]
**Blog RSS Feed URL:
https://blogs.oracle.com/theaquarium/rss

**Author Name"
Will Lyons

**Why should we add this blog to Jakartablogs.ee?
As Member of the Steering Committee I post Jakarta EE related blogs to this site.

** Profile Picture:
![Jakarta EE picture](https://user-images.githubusercontent.com/28606725/72294673-732fbe80-366f-11ea-96d5-4cbb71c7d1cd.jpg)

**Comment by chrisguindon** [comment]
You post are now showing on the website! Thanks for the issue!
