### ISSUE TITLE
Add Gunnar Morling's blog

### ISSUE THREAD

**Issue by gunnarmorling** [jakartaee/jakartablogs.ee#62]
**Blog RSS Feed URL:
https://www.morling.dev/tags/jakartaee/index.xml

**Author Name"
Gunnar Morling

**Why should we add this blog to Jakartablogs.ee?
I'm the lead of the Jakarta Bean Validation spec and blog occasionally about Jakarta related topics.

** Profile Picture:
![gunnar_morling_speaker_profile_185](https://user-images.githubusercontent.com/28612/72827423-0cb42d00-3c7b-11ea-9c48-32cdbc1437b5.jpg)

Thanks a lot!

**Comment by chrisguindon** [comment]
Thanks
