### ISSUE TITLE
Add Thorben Janssen's blog (thoughts-on-java.org)

### ISSUE THREAD

**Issue by thjanssen** [jakartaee/jakartablogs.ee#63]
**Blog RSS Feed URL:
https://thoughts-on-java.org/feed/

**Author Name"
Thorben Janssen

**Why should we add this blog to Jakartablogs.ee?
I have been involved with the Java EE/Jakarta EE community for several years. I blog and wrote a book about Java persistence topics, especially JPA and Hibernate. I'm also speaking at conferences and teaching workshops about these topics. 
During the development of Java EE 8, I was part of the CDI 2.0 expert group.

** Profile Picture:
![rsz_1rsz_foto_thorben_janssen](https://user-images.githubusercontent.com/2053825/73628921-e36ba780-4651-11ea-9a89-2142930a9226.jpg)

**Comment by chrisguindon** [comment]
Thanks!
