### ISSUE TITLE
[Blog post] Keeping Brazil’s Medical Industry Safe with MicroProfile & JakartaEE – Jakarta Tech Talks

### ISSUE THREAD

**Issue by cesarhernandezgt** [jakartaee/jakartablogs.ee#70]
**Blog RSS Feed URL:
https://www.tomitribe.com/blog/keeping-brazils-medical-industry-safe-with-microprofile-jakartaee-jakarta-tech-talks/feed/

**Author Name"
Rafael Guimares
Cesar Hernandez

**Why should we add this blog to Jakartablogs.ee?
This is a blog post related to a cloud migration from JavaEE into Eclipse MicroProfile, JakartaEE, and microservices architecture.

** Profile Picture:
![rsz_1smartselect_20190903-163026_gallery](https://user-images.githubusercontent.com/1454523/82612336-dda5bd80-9b7f-11ea-9e78-fc9efb827707.jpg)

![rsz_1454523](https://user-images.githubusercontent.com/1454523/82612418-0b8b0200-9b80-11ea-8633-c1d560d8fd92.jpg)

**Comment by chrisguindon** [comment]
@cesarhernandezgt We can only use 1 picture per feed. Which one should we use?

**Comment by cesarhernandezgt** [comment]
@chrisguindon 

Please use the following image:

![newImage](https://user-images.githubusercontent.com/1454523/83899487-c802cd00-a715-11ea-98a6-02dcdbb58f68.png)

**Comment by chrisguindon** [comment]
Thanks @cesarhernandezgt

**Comment by cesarhernandezgt** [comment]
Hi @chrisguindon ,
I don't see the blog post in the `https://jakartablogs.ee/#main-content`, is there anything I miss in my submission? 

I do see the blog URL on the list under `https://jakartablogs.ee/#blogs`, but the actual content doesn't appear on the `https://jakartablogs.ee/#main-content`.

**Comment by chrisguindon** [comment]
@cesarhernandezgt Did your feed change?
https://www.tomitribe.com/blog/keeping-brazils-medical-industry-safe-with-microprofile-jakartaee-jakarta-tech-talks/feed/

I would expect to see the content of your post in your feed. For example, this is mine: https://www.chrisguindon.com/index.xml

**Comment by cesarhernandezgt** [comment]
Thanks @chrisguindon for the pointer.
I'm going to check the feed because I see our blog post only has relative paths.
