### ISSUE TITLE
Could you add my new blog?

### ISSUE THREAD

**Issue by thadumi** [jakartaee/jakartablogs.ee#72]
**Blog RSS Feed URL:
https://thadumi.com/tag/jakartaee/rss/

**Author Name"
Theodor Augustin Dumitrescu

**Why should we add this blog to Jakartablogs.ee?
 As discussed during the Friends of JakartaEE call, I'm starting this blog for writing short code snippets about JakartaEE.  

** Profile Picture:
![55218d0e-e311-425a-abd0-cabd630acc37](https://user-images.githubusercontent.com/19282590/85809044-f1cc7400-b756-11ea-8bef-0725ff6273a9.jpg)

**Comment by aeiras** [comment]
Your actions are AMAZING Theodor!
