### ISSUE TITLE
Jakarta EE 9 Milestone and Apache TomEE 9.0.0 M1

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakartablogs.ee#76]
**Blog RSS Feed URL:
https://www.tomitribe.com/blog/jakarta-ee-9-milestone-and-apache-tomee-9-0-0-m1/

**Author Name"
David Blevins

**Why should we add this blog to Jakartablogs.ee?
It deals with the Jakarta EE 9 Milestone release activity

** Profile Picture:

![DB-pic](https://user-images.githubusercontent.com/10731224/86037524-59ebb600-b9f4-11ea-9869-560d8e1f2966.png)

Thanks,

**Comment by ivargrimstad** [comment]
Hi @aeiras! 

The blog aggregator needs an RSS feed.
Can you confirm that this is the feed we should use:

[https://www.tomitribe.com/blog/category/jakarta-ee/feed/](https://www.tomitribe.com/blog/category/jakarta-ee/feed/)

This will feed all posts in the Jakarta EE category from the Tomitribe blog into JakartaBlogs.

**Comment by aeiras** [comment]
Hola Ivar :) 

There are 2 tasks we want to achieve, YES to adding the Tomitribe Blogs as the Company summary of all TT blogs. If you could help with that with this ticket, that would be much appreciated Ivar. 

Now, with the help of the EF team who helps on adding blogs to the Jakarta EE space, we discovered something that is prohibiting us from doing it, currently the Team is fixing that bug. That means, that this single blog with its respective link, just as Cesar's blog,  won't be able to be a part of the aggregator until we fix that bug. 

Please ask away and thanks @ivargrimstad!

**Comment by aeiras** [comment]
@ivargrimstad can we use instead this feed: https://www.tomitribe.com/blog/

?

**Comment by aeiras** [comment]
OR this: 
https://www.tomitribe.com/blog/category/jakarta-ee/

**Comment by cesarhernandezgt** [comment]
@aeiras the feed @ivargrimstad is asking for is the format that the jakartablogs website automatically read.
Base on the URL from the description, the feed would be: https://www.tomitribe.com/blog/jakarta-ee-9-milestone-and-apache-tomee-9-0-0-m1/feed/

**Comment by aeiras** [comment]
@cesarhernandezgt 

This ticket has transcended the individual blog. 2 tasks 1 ticket. 
We want to also add the Tomitribe Blogs as a corporate contributor to the Jakarta EE content. Currently, only 3 corporate ORGs have done so. Therefore, that links needs to be under the Jakarta category content link : 
https://www.tomitribe.com/blog/category/jakarta-ee/

<img width="403" alt="image" src="https://user-images.githubusercontent.com/10731224/86046816-bd7ce000-ba02-11ea-8cca-38d47566803e.png">

Thanks to both, Ivar & Cesar!

**Comment by ivargrimstad** [comment]
I have created a PR to add the Tomitribe Blog. https://github.com/jakartaee/jakartablogs.ee/pull/77

**Comment by aeiras** [comment]
Thank you for working with us while we fix the internal bug Ivar. 

For now, adding the TT blog with Jakarta category is perfect! We plan to add Triber's content as well-- that comes after the fix. :)

**Comment by ivargrimstad** [comment]
https://jakartablogs.ee/#blogs
