### ISSUE TITLE
[Blog post] Jakarta EE Cookbook

### ISSUE THREAD

**Issue by eldermoraes** [jakartaee/jakartablogs.ee#78]
**Blog RSS Feed URL:
https://eldermoraes.com/jakarta-ee-cookbook/feed/

**Author Name"
Elder Moraes

**Why should we add this blog to Jakartablogs.ee?
This blog post shows to the readers some details about the Jakarta EE Cookbook, one of the most practical and complete references about Jakarta EE in this market.

** Profile Picture:
![](https://eldermoraes.com/wp-content/uploads/2020/07/avatar-185x185-1.png)

**Comment by aeiras** [comment]
always beautiful & awesome Elder :)

**Comment by eldermoraes** [comment]
Thanks, Amelia! :-)

**Comment by eldermoraes** [comment]
I think I misunderstood something... I thought I should submit a blog post, not a whole blog per se. Sorry!

Is it possible to change the feed to https://eldermoraes.com/category/jakartaee/feed/?

**Comment by eldermoraes** [comment]
Should I open another issue instead?

**Comment by ivargrimstad** [comment]
I'll fix it :)

**Comment by eldermoraes** [comment]
Thank you, Ivar!
