### ISSUE TITLE
Adding Jelastic PaaS Blog Feed to Jakarta Blogs

### ISSUE THREAD

**Issue by TetianaFTV** [jakartaee/jakartablogs.ee#84]
**Blog RSS Feed URL: 
https://jelastic.com/blog/category/java/feed/

**Author Name"
Tetiana Fydorenchyk

**Why should we add this blog to Jakartablogs.ee?
Jelastic PaaS blog is about Java, Jakarta, cloud technologies, DevOps, containers, etc. We publish updates about support of Jakarta EE versions within the cloud platform.

** Profile Picture:
![Tetiana Fydorenchyk copy](https://user-images.githubusercontent.com/38689227/89876724-58023e80-dbbf-11ea-900f-8bd496b1df09.JPG)

**Comment by aeiras** [comment]
You are fantastic @TetianaFTV 💪🏼🥰

**Comment by aeiras** [comment]
Hola @ivargrimstad,

Pulling you in as I have done via private but this time to ask you if via Jakarta EE Studio Youtube platform, we can use 30mins video interview to highlight the Jelastic Team work via a nice Q&A. 

The Q&A needs to/out to be prepared by the Marketing Committee as Group 2 matters greatly and cannot be done, just b/c. 

Thanks for the follow up and the focus!

**Comment by ivargrimstad** [comment]
> Hola @ivargrimstad,
> 
> Pulling you in as I have done via private but this time to ask you if via Jakarta EE Studio Youtube platform, we can use 30mins video interview to highlight the Jelastic Team work via a nice Q&A.
> 
> The Q&A needs to/out to be prepared by the Marketing Committee as Group 2 matters greatly and cannot be done, just b/c.
> 
> Thanks for the follow up and the focus!

I'll contact @TetianaFTV to set up an interview or similar. 
Will close this issue as the blog has been added.

**Comment by aeiras** [comment]
You are fantastic #usualsuspects!

**Comment by TetianaFTV** [comment]
Thank you, @ivargrimstad! 
i'll be glad to get in touch soon.
