### ISSUE TITLE
JakartaONE Español 2020: De Comunidad Para Comunidad!

### ISSUE THREAD

**Issue by aeiras** [jakartaee/jakartablogs.ee#86]
**Blog RSS Feed URL:
For example, https://www.tomitribe.com/blog/jakartaone-espanol-2020-de-comunidad-para-comunidad/?

**Author Name"
Amelia Eiras.

**Why should we add this blog to Jakartablogs.ee?
It is about JakartaONE Español 2020

** Profile Picture:

**Comment by chrisguindon** [comment]
@aeiras can you provide an RSS feed for this blog?
https://github.com/jakartaee/jakartablogs.ee#how-to-add-your-blog

For example, https://blogs.eclipse.org/blog/180/feed

**Comment by chrisguindon** [comment]
Closing this issue since we are still missing the RSS feed.

**Comment by cesarhernandezgt** [comment]
As a complementary note, the blog post originally reported in this ticket was missing the category `Jakarta EE`, the category is now included in the blog post. I guess it just a matter of timing for the https://jakartablogs.ee/ to re-index the feeds.
