### ISSUE TITLE
Add Webtide Jakarta Blogs to Jakarta feed

### ISSUE THREAD

**Issue by WalkerWatch** [jakartaee/jakartablogs.ee#89]
**Blog RSS Feed URL:
https://webtide.com/category/jakarta/feed/

**Author Name"
Chris Walker, et. al.

**Why should we add this blog to Jakartablogs.ee?
Blogs detail both Webtide (as Jetty and cometD) and community efforts to adopt and push Jakarta forward.

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by WalkerWatch** [comment]
![1237580](https://user-images.githubusercontent.com/1237580/104343471-96c75800-54c1-11eb-816b-0a65066ccb19.jpg)

**Comment by WalkerWatch** [comment]
![1237580](https://user-images.githubusercontent.com/1237580/104343635-cb3b1400-54c1-11eb-86d9-b71f38ef3e6c.jpg)

**Comment by ivargrimstad** [comment]
Just noted that the Webtide blog is already listed. @WalkerWatch Do you want me to switch the logo with your photo? Or keep as it is?

**Comment by WalkerWatch** [comment]
Oh, sorry, wasn't aware. Keep the logo, please.

**Comment by ivargrimstad** [comment]
It points to https://webtide.com/category/jakarta/feed/, which should be correct. Your latest post does not appear on the site though. Not sure why. It looks correct to me. Maybe @chrisguindon can figure it out?

**Comment by chrisguindon** [comment]
@ivargrimstad the patch that you submited has a syntax error:
https://github.com/ivargrimstad/jakartablogs.ee/commit/26d25b738ca38f737e40c8abede5ed2945e3a03d#diff-bc9085f37b09738f4e48e7f926c54c428dd7423ce18cdd8d467045e9333f021cR216

You are missing an equal sign:
picture chris-walker.jpg

**Comment by chrisguindon** [comment]
@ivargrimstad I see now, the problem seems to be with the existing webtide feed?

**Comment by ivargrimstad** [comment]
Yes, correct. I noticed that when created the PR for this issue. I'll withdraw my PR anyway. But we should try to figure out why the webtide feed isn't showing up

**Comment by chrisguindon** [comment]
+1 from what I can tell, the feed is properly configured. I can see two Webtide blog posts on the page but the latest one is not showing...

Must be something in the post that planetvenus does not like. We will probably need to access our logs to see the error.

**Comment by chrisguindon** [comment]
I started a new build and I can now see the latest blog post from webtide! Closing this issue.
