### ISSUE TITLE
Deep Dive Faith

### ISSUE THREAD

**Issue by DarrenAllen787** [jakartaee/jakartablogs.ee#93]
**Blog RSS Feed URL:
https://deepdivefaith.blogspot.com

**Author Name"
Darren Allen

**Why should we add this blog to Jakartablogs.ee?
Describe in your own words what this blog is about and why we should add this new blog to jakartablogs.ee.
	Hello, my name is Darren if you are at all curious why I am doing this blog, the short answer is God loves you and I want to learn to love like God. I don't know it all, nor do I have it all figured out, please don't look to me, rather look to Jesus, I do. Second I want nothing from you, other than for you to know that you are deeply loved and of immeasurable worth. Other than your prayers, which I would gladly have, if you ever see me ask for money or anything like that from you or anyone, then its not me! It was freely given to me and I freely give it to those who are interested. That's why I do what I do, because he did it first. God Bless

** Profile Picture:
If you with to include your profile picture, please attach a 185x185 jpg or png to this issue.

**Comment by ivargrimstad** [comment]
Does not belong here
