### ISSUE TITLE
Add Jakarta EE Ambassadors Blog

### ISSUE THREAD

**Issue by m-reza-rahman** [jakartaee/jakartablogs.ee#94]
**Blog RSS Feed URL:
For example: https://jakartaee-ambassadors.io/blog/feed/

**Author Name"
Jakarta EE Ambassadors

**Why should we add this blog to Jakartablogs.ee?
This is the official Jakarta EE Ambassadors blog. Important joint positions and updates are usually published here.

** Profile Picture:
![jakartaee_ambassadors_logo](https://user-images.githubusercontent.com/3622346/119205960-d43b8380-ba67-11eb-9486-9b98e11191f7.png)

**Comment by m-reza-rahman** [comment]
Could the latest entry kindly be added? It is fairly important: https://jakartaee-ambassadors.io/2021/05/10/jakarta-ee-ambassadors-joint-position-on-jakarta-ee-and-microprofile-alignment/.

**Comment by linkfang** [comment]
Hi @m-reza-rahman 
Jakarta EE Ambassadors was added to the blog list.
It's live now: https://jakartablogs.ee/#blogs

You can find all posts from Jakarta EE Ambassadors in the "Latest posts" list. They are ordered by dates, so you have to scroll down a little bit to see the latest entry from Jakarta EE Ambassadors.

**Comment by alliancecoder** [comment]
> 
> 
> Hi @m-reza-rahman
> Jakarta EE Ambassadors was added to the blog list.
> It's live now: https://jakartablogs.ee/#blogs
> 
> You can find all posts from Jakarta EE Ambassadors in the "Latest posts" list. They are ordered by dates, so you have to scroll down a little bit to see the latest entry from Jakarta EE Ambassadors.

Thanks for compiling this list! Clicking the first link returns an error. I believe Adam Bien's link requires a trailing slash; https://adambien.blog/roller/

**Comment by linkfang** [comment]
> 
> Thanks for compiling this list! Clicking the first link returns an error. I believe Adam Bien's link requires a trailing slash; https://adambien.blog/roller/

Good catch! 
I opened another issue for it and will close this one.
https://github.com/jakartaee/jakartablogs.ee/issues/96
