### ISSUE TITLE
Invalid URLs for some blogs in Blogs tab

### ISSUE THREAD

**Issue by linkfang** [jakartaee/jakartablogs.ee#96]
Blogs url: https://jakartablogs.ee/#blogs

The one that is broken:
- Adam Bien - removed by [PR99](https://github.com/jakartaee/jakartablogs.ee/pull/99)

The ones that do not have a valid feed url:

- Altuğ B. Altıntaş - removed by [PR97](https://github.com/jakartaee/jakartablogs.ee/pull/97)
-  Hayri Cicek - reomved by [PR98](https://github.com/jakartaee/jakartablogs.ee/pull/98)

**Comment by alliancecoder** [comment]
It isn't broken, it needs a trailing slash

[Adam Bien's Blog](https://adambien.blog/roller/)

The one that is broken:

    Adam Bien - removed by PR99

**Comment by linkfang** [comment]
> It isn't broken, it needs a trailing slash
> 
> [Adam Bien's Blog](https://adambien.blog/roller/)
> 
> The one that is broken:
> 
> ```
> Adam Bien - removed by PR99
> ```

Hi,

Yeah, I know when we add a slash at the end it will work properly. But I am afraid it's something that Adam has to fix on his side. The reason it misses a slash is because it is not properly set up in his feed/rss page.

And no worries, @chrisguindon knows Adam and will add him into the PR99 to see if he could fix it on his end.
BTW, I am guessing you are not Adam?

**Comment by alliancecoder** [comment]
Correct - I follow Adam and started following this community to try to contribute. Thanks for the follow-up!

**Comment by linkfang** [comment]
> Correct - I follow Adam and started following this community to try to contribute. Thanks for the follow-up!

OK, cool! No problem!
I was worrying I was talking to Adam without realizing it😂

Thanks for bring up the issue!

**Comment by chrisguindon** [comment]
I believe we use the `<link>` URLs provided in the RSS feed.
